version: "3.9"
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8083:80"
    environment:
      - TZ=Europe/London
      - WEBPASSWORD=changeme
    volumes:
      - pihole_data:/etc/pihole
      - dnsmasq_data:/etc/dnsmasq.d

volumes:
  pihole_data:
  dnsmasq_data:
